Basic avoid basic trap
chrisrabe/ai-sports-2021 pull request #69
Opened 2021-04-26 12:44 UTC by Antimatter543

probably be issues with bomb_tracker

2021-04-26 21:55 UTC, Antimatter543 commented
Maybe not approve until I add the trapping mechanisms + fix conflicts (although if you need the avoid_bomb strat, go ahead).

2021-04-26 22:02 UTC, chrisrabe requested changes
get_blast_zone has bugs. Also no need to create a new key for your strategy. Can just replace what's in retreat

2021-04-26 22:02 UTC, chrisrabe commented on python3/totoro_agent/utils/util_functions.py
> +            cur_loc = bomb_loc
can remove this

2021-04-26 22:47 UTC, Antimatter543 commented on python3/totoro_agent/brain/brain.py
> +            return 'basic_avoid' # Basic avoid vs retreat. Retreat value based, basic avoid is coded.
Got it. I'll copy paste your blast_zone func from develop into this branch once at home.

2021-04-27 14:04 UTC, chrisrabe approved these changes

2021-04-27 14:04 UTC, merged